name : Deploy to EC2

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing connect to server using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/Immersive-Dashboard-App-Project
            git pull origin main
            docker stop gp3container
            docker rm gp3container
            docker rmi alvinashki/gp3image:latest
            docker build -t alvinashki/gp3image:latest .
            docker run -d -p 80:8000 -e AWS_BUCKET=${{ secrets.AWS_BUCKET }} -e AWS_REGION=${{ secrets.AWS_REGION }} -e S3_KEY=${{ secrets.S3_KEY }} -e S3_SECRET=${{ secrets.S3_SECRET }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e SERVER_PORT=${{ secrets.SERVER_PORT }} --name gp3container alvinashki/gp3image:latest
             
       
